<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCtthbcl\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCtthbcl/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCtthbcl.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCtthbcl\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCtthbcl\appProdProjectContainer([
    'container.build_hash' => 'Ctthbcl',
    'container.build_id' => 'ecb7dc01',
    'container.build_time' => 1565069087,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCtthbcl');
