services:
    service.repository.product:
        class: AppBundle\Repository\ProductRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Product
        lazy: true
