<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'jms_di_extra.metadata_driver' shared service.

include_once $this->targetDirs[3].'\\vendor\\jms\\metadata\\src\\Metadata\\Driver\\DriverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\jms\\di-extra-bundle\\Metadata\\Driver\\AnnotationDriver.php';
include_once $this->targetDirs[3].'\\vendor\\jms\\di-extra-bundle\\Metadata\\NamingStrategy.php';
include_once $this->targetDirs[3].'\\vendor\\jms\\di-extra-bundle\\Metadata\\DefaultNamingStrategy.php';

return $this->services['jms_di_extra.metadata_driver'] = new \JMS\DiExtraBundle\Metadata\Driver\AnnotationDriver(${($_ = isset($this->services['annotation_reader']) ? $this->services['annotation_reader'] : $this->getAnnotationReaderService()) && false ?: '_'}, ${($_ = isset($this->services['jms_di_extra.service_naming_strategy']) ? $this->services['jms_di_extra.service_naming_strategy'] : ($this->services['jms_di_extra.service_naming_strategy'] = new \JMS\DiExtraBundle\Metadata\DefaultNamingStrategy())) && false ?: '_'});
