<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'jms_di_extra.service_naming_strategy' shared service.

include_once $this->targetDirs[3].'\\vendor\\jms\\di-extra-bundle\\Metadata\\NamingStrategy.php';
include_once $this->targetDirs[3].'\\vendor\\jms\\di-extra-bundle\\Metadata\\DefaultNamingStrategy.php';

return $this->services['jms_di_extra.service_naming_strategy'] = new \JMS\DiExtraBundle\Metadata\DefaultNamingStrategy();
