<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'jms_di_extra.metadata.converter' shared service.

include_once $this->targetDirs[3].'\\vendor\\jms\\di-extra-bundle\\Metadata\\MetadataConverter.php';

return $this->services['jms_di_extra.metadata.converter'] = new \JMS\DiExtraBundle\Metadata\MetadataConverter();
