<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJmgh7tq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJmgh7tq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJmgh7tq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJmgh7tq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJmgh7tq\appDevDebugProjectContainer([
    'container.build_hash' => 'Jmgh7tq',
    'container.build_id' => '5ccec009',
    'container.build_time' => 1564976607,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJmgh7tq');
