<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVzqwauh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVzqwauh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVzqwauh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVzqwauh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVzqwauh\appDevDebugProjectContainer([
    'container.build_hash' => 'Vzqwauh',
    'container.build_id' => 'dfd85151',
    'container.build_time' => 1565097099,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVzqwauh');
